name: "tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  test_linux_20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        counter: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    steps:
    - run: echo "Yo I am Ubuntu 20.04" ${{ matrix.counter }}

  test_linux_18:
    environment: "ubuntu-18-04-env"
    strategy:
      fail-fast: false
      matrix:
        counter: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    name: Ubuntu 18.04 / ${{ matrix.counter }}
    runs-on: ubuntu-18.04
    steps:
    - run: echo "Yo I am Ubuntu 18.04" ${{ matrix.counter }}
