name: "tests"
environment: "ubuntu-18-04-env"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  test_linux_20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - run: echo "Yo I am Ubuntu 20.04"

  test_linux_18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - run: echo "Yo I am Ubuntu 18.04"
